options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _NEXT_PUBLIC_IDP_BASE_URL_PROD: 'https://identity.ethanswan.com'
  _NEXT_PUBLIC_IDP_BASE_URL_STAGING: 'https://identity-staging.tailc06f30.ts.net'
  _SENTRY_ORG: 'forecasting'
  _SENTRY_PROJECT: 'forecasting-app'
  _IMAGE: 'us-central1-docker.pkg.dev/ethans-services/containers/forecasting'

availableSecrets:
  secretManager:
    - versionName: projects/ethans-services/secrets/forecasting_sentry_auth_token/versions/latest
      env: 'SENTRY_AUTH_TOKEN'

steps:
  # Build prod image (with BuildKit layer caching to avoid re-running npm ci)
  - id: 'build-prod'
    name: 'gcr.io/cloud-builders/docker'
    waitFor: ['-']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker buildx create --use --name builder-prod
        docker buildx build \
          --cache-from type=registry,ref=${_IMAGE}:cache-prod \
          --cache-to type=registry,ref=${_IMAGE}:cache-prod,mode=max \
          --push \
          --build-arg NEXT_PUBLIC_IDP_BASE_URL=${_NEXT_PUBLIC_IDP_BASE_URL_PROD} \
          --build-arg SENTRY_ORG=${_SENTRY_ORG} \
          --build-arg SENTRY_PROJECT=${_SENTRY_PROJECT} \
          --build-arg SENTRY_AUTH_TOKEN=$$SENTRY_AUTH_TOKEN \
          -t ${_IMAGE}:${SHORT_SHA}-prod \
          -t ${_IMAGE}:prod \
          .
    secretEnv: ['SENTRY_AUTH_TOKEN']
  # Build staging image (with BuildKit layer caching to avoid re-running npm ci)
  - id: 'build-staging'
    name: 'gcr.io/cloud-builders/docker'
    waitFor: ['-']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker buildx create --use --name builder-staging
        docker buildx build \
          --cache-from type=registry,ref=${_IMAGE}:cache-staging \
          --cache-to type=registry,ref=${_IMAGE}:cache-staging,mode=max \
          --push \
          --build-arg NEXT_PUBLIC_IDP_BASE_URL=${_NEXT_PUBLIC_IDP_BASE_URL_STAGING} \
          --build-arg SENTRY_ORG=${_SENTRY_ORG} \
          --build-arg SENTRY_PROJECT=${_SENTRY_PROJECT} \
          --build-arg SENTRY_AUTH_TOKEN=$$SENTRY_AUTH_TOKEN \
          -t ${_IMAGE}:${SHORT_SHA}-staging \
          -t ${_IMAGE}:staging \
          .
    secretEnv: ['SENTRY_AUTH_TOKEN']
