version: '3'

services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpw
      POSTGRES_DB: forecasting
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d forecasting"]
      interval: 3s
      timeout: 4s
      retries: 5
    ports:
      - 2345:5432

  cloner:
    image: postgres:17
    environment:
      POSTGRES_USER: abc
      POSTGRES_PASSWORD: def
      POSTGRES_DB: nonsense
      LOCAL_DB_URI: "postgresql://admin:adminpw@host.docker.internal:2345/forecasting"
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      bash -c "pg_dump --no-owner --no-acl $DATABASE_URL | psql 'postgresql://admin:adminpw@host.docker.internal:2345/forecasting'"

    
