apiVersion: v1
kind: ServiceAccount
metadata:
  name: haruspex-staging-ksa
  namespace: haruspex-staging
  annotations:
    iam.gke.io/gcp-service-account: haruspex-staging-sa@ethans-services.iam.gserviceaccount.com
