/**
 * Compiles `migrations/` plus `lib/migrations/runner.ts` into a single
 * self-contained script, `dist/migrate/index.js`, that the Dockerfile copies
 * into the runtime image as `/app/migrate/index.js`.
 *
 * Why compile at all: bifrost preview environments run an initContainer from
 * the app image to bring a freshly branched database up to date before the app
 * starts (the other onboarded apps use `["alembic", "upgrade", "head"]` and
 * `["/app/auth-service", "migrate"]`). forecasting has no equivalent — the
 * runner stage carries neither `kysely-ctl` nor `tsx`, so nothing there can load
 * a `.ts` migration. Without this, a preview whose Neon branch is behind its
 * code would crashloop on the startup check with no way to move forward.
 *
 * Why a bundle rather than copied files: the bundle inlines `kysely` and `pg`,
 * so the runner needs nothing from `node_modules` at all. Next's standalone
 * file tracing does not currently emit `kysely` into
 * `.next/standalone/node_modules`, and what it does emit is an implementation
 * detail that can change between Next releases — migrations breaking silently
 * because tracing changed is not a failure mode worth having.
 *
 * Usage:
 *   node scripts/build-migration-runner.ts     (also run by `npm run build`)
 */

import { promises as fs } from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

import * as esbuild from "esbuild";

import { MIGRATION_MANIFEST } from "../lib/migrations/manifest.ts";
import { REPO_ROOT, readMigrationNames } from "./generate-migration-manifest.ts";

export const DEFAULT_OUT_DIR = path.join(REPO_ROOT, "dist", "migrate");

/** The runner module the generated entry point drives. */
const RUNNER_MODULE = "./lib/migrations/runner";

/**
 * Renders the entry point esbuild compiles.
 *
 * It is generated rather than committed because it is pure mechanism — one
 * static import per migration, which is what lets esbuild see them — and a
 * committed copy would be one more thing to keep in step with `migrations/`.
 * `lib/migrations/manifest.ts` is the committed list, and this is checked
 * against it both here and inside the compiled runner itself.
 *
 * Only `migrations/` is ever read. In particular the test harness's
 * `00000000_bootstrap` migration lives in `tests/helpers/` and is not a
 * migration; nothing here can reach it.
 */
export function renderEntry(names: readonly string[]): string {
  const imports = names
    .map((name, index) => `import * as m${index} from "./migrations/${name}.ts";`)
    .join("\n");

  const entries = names
    .map((name, index) => `  ${JSON.stringify(name)}: m${index},`)
    .join("\n");

  return `// Generated by scripts/build-migration-runner.ts at build time. Not committed.
import { runMigrationCli } from "${RUNNER_MODULE}";
${imports}

const MIGRATIONS = {
${entries}
};

process.exit(await runMigrationCli(MIGRATIONS));
`;
}

/**
 * Fails the build when `migrations/` and the committed manifest disagree.
 *
 * The startup check reads the manifest; the runner applies what is compiled. If
 * those two sets ever differ, a preview migrates "successfully" and then the app
 * refuses to boot against the result. `lib/migrations/manifest.test.ts` catches
 * the same drift in CI — this catches it in the Docker build too, where no test
 * runs.
 */
export function assertMatchesManifest(names: readonly string[]): void {
  const found = [...names].sort();
  const expected = [...MIGRATION_MANIFEST].sort();

  if (found.length === expected.length && found.every((n, i) => n === expected[i])) {
    return;
  }

  const foundSet = new Set(found);
  const expectedSet = new Set(expected);

  throw new Error(
    [
      "migrations/ and lib/migrations/manifest.ts disagree, so the migration",
      "runner cannot be built. Run `npx tsx scripts/generate-migration-manifest.ts`",
      "and commit the result.",
      `  In migrations/ but not the manifest: ${found.filter((n) => !expectedSet.has(n)).join(", ") || "(none)"}`,
      `  In the manifest but not migrations/: ${expected.filter((n) => !foundSet.has(n)).join(", ") || "(none)"}`,
    ].join("\n"),
  );
}

export interface BuildResult {
  outDir: string;
  outFile: string;
  names: string[];
  bytes: number;
}

export async function buildMigrationRunner(
  outDir: string = DEFAULT_OUT_DIR,
): Promise<BuildResult> {
  const names = await readMigrationNames();
  assertMatchesManifest(names);

  const outFile = path.join(outDir, "index.js");

  await esbuild.build({
    stdin: {
      contents: renderEntry(names),
      resolveDir: REPO_ROOT,
      sourcefile: "migrate-entry.ts",
      loader: "ts",
    },
    bundle: true,
    platform: "node",
    format: "esm",
    target: "node24",
    outfile: outFile,
    // `pg` optionally requires its native binding, which is not installed. The
    // require sits behind a lazy getter in a try/catch that we never trigger.
    external: ["pg-native"],
    // esbuild's ESM output rewrites CommonJS `require` (which `pg` uses for
    // node builtins) into a shim that throws unless a real `require` is in
    // scope. Give it one.
    banner: {
      js: [
        "import { createRequire as __createRequire } from 'node:module';",
        "const require = __createRequire(import.meta.url);",
      ].join("\n"),
    },
    legalComments: "none",
    minify: false,
  });

  // Declares the bundle's module format for itself, rather than inheriting it
  // from whatever package.json happens to sit above it in the image.
  await fs.writeFile(
    path.join(outDir, "package.json"),
    `${JSON.stringify({ name: "haruspex-migrate", private: true, type: "module" }, null, 2)}\n`,
    "utf8",
  );

  const { size } = await fs.stat(outFile);
  return { outDir, outFile, names, bytes: size };
}

async function main(): Promise<void> {
  const result = await buildMigrationRunner();
  console.log(
    `Compiled ${result.names.length} migration(s) into ${path.relative(REPO_ROOT, result.outFile)} (${Math.round(result.bytes / 1024)} KiB)`,
  );
}

// Only run when invoked directly, so tests can import the helpers above.
if (
  process.argv[1] &&
  path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)
) {
  await main();
}
