/**
 * Regenerates `lib/migrations/manifest.ts` from the contents of `migrations/`.
 *
 * The manifest is the list of migration names this build knows about. It has to
 * be a committed source file rather than a build artifact: the runtime image
 * never sees `migrations/` (the Dockerfile's runner stage copies only
 * `.next/standalone` and `.next/static`), and `next dev`, `vitest`, `tsc
 * --noEmit` and `eslint` all need it to exist without anyone having run a build
 * first.
 *
 * Drift between this file and `migrations/` is caught by
 * `lib/migrations/manifest.test.ts`, which re-renders the manifest with the
 * functions below and compares it byte-for-byte against what is on disk.
 *
 * Usage:
 *   npx tsx scripts/generate-migration-manifest.ts
 */

import { promises as fs } from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));

export const REPO_ROOT = path.resolve(scriptDir, "..");
export const MIGRATIONS_DIR = path.join(REPO_ROOT, "migrations");
export const MANIFEST_PATH = path.join(
  REPO_ROOT,
  "lib",
  "migrations",
  "manifest.ts",
);

/**
 * Reads the migration names from `migrations/`.
 *
 * A migration's name is its filename with the extension stripped — that is what
 * both kysely-ctl's `TSFileMigrationProvider` (which `npm exec kysely migrate
 * up` uses) and kysely's own `FileMigrationProvider` (which the test harness
 * uses) store in the migration table. Only `.ts` files count, because
 * kysely-ctl's `allowJS` defaults to false and so it ignores everything else.
 *
 * The result is sorted, matching the order kysely applies migrations in.
 */
export async function readMigrationNames(
  migrationsDir: string = MIGRATIONS_DIR,
): Promise<string[]> {
  const entries = await fs.readdir(migrationsDir, { withFileTypes: true });
  return entries
    .filter((entry) => entry.isFile() && entry.name.endsWith(".ts"))
    .map((entry) => entry.name.slice(0, -".ts".length))
    .sort();
}

/** Renders the full text of `lib/migrations/manifest.ts` for a set of names. */
export function renderManifest(names: readonly string[]): string {
  const entries = names.map((name) => `  ${JSON.stringify(name)},\n`).join("");

  return `// Code generated by scripts/generate-migration-manifest.ts. DO NOT EDIT.
//
// Run \`npx tsx scripts/generate-migration-manifest.ts\` after adding, removing
// or renaming a migration. \`lib/migrations/manifest.test.ts\` fails if this file
// and \`migrations/\` disagree, so drift cannot reach main.
//
// This exists so the startup check in \`instrumentation.ts\` knows which
// migrations the build expects without reading \`migrations/\` — the runtime
// image does not contain that directory. Names are filenames minus the \`.ts\`
// extension, which is exactly what kysely records in its migration table.

export const MIGRATION_MANIFEST: readonly string[] = [
${entries}];
`;
}

async function main(): Promise<void> {
  const names = await readMigrationNames();
  await fs.writeFile(MANIFEST_PATH, renderManifest(names), "utf8");
  console.log(
    `Wrote ${names.length} migration name(s) to ${path.relative(REPO_ROOT, MANIFEST_PATH)}`,
  );
}

// Only run when invoked directly, so the test can import the helpers above.
if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  await main();
}
