import type { PropView } from "./types";

const day = (n: number) => new Date(Date.UTC(2026, 8, 2) + n * 86_400_000);

/**
 * Past the deadline, awaiting a result. Covers all three prop kinds, a prop the
 * viewer never forecasted, and a near-coin-flip.
 */
export const unresolvedFixture: PropView[] = [
  {
    propId: 1,
    text: "A European country wins the 2026 FIFA Men's World Cup.",
    category: "Sports",
    kind: "binary",
    yourForecast: 0.72,
    communityAverage: 0.64,
    outcome: null,
    options: [],
    resolved: false,
    closedAt: day(-12),
  },
  {
    propId: 2,
    text: "Keir Starmer is the prime minister of the UK at the end of 2026.",
    category: "World politics",
    kind: "binary",
    yourForecast: 0.45,
    communityAverage: 0.58,
    outcome: null,
    options: [],
    resolved: false,
    closedAt: day(-12),
  },
  {
    propId: 3,
    text: "Which party holds the most seats after the next general election?",
    category: "World politics",
    kind: "one_of",
    yourForecast: null,
    communityAverage: null,
    outcome: null,
    options: [
      {
        optionId: 31,
        text: "Labour",
        yourForecast: 0.55,
        communityAverage: 0.48,
        outcome: null,
      },
      {
        optionId: 32,
        text: "Conservative",
        yourForecast: 0.3,
        communityAverage: 0.34,
        outcome: null,
      },
      {
        optionId: 33,
        text: "Reform",
        yourForecast: 0.15,
        communityAverage: 0.18,
        outcome: null,
      },
    ],
    resolved: false,
    closedAt: day(-30),
  },
  {
    propId: 4,
    text: "Which of these ship a consumer AI device before 2027?",
    category: "Technology",
    kind: "any_of",
    yourForecast: null,
    communityAverage: null,
    outcome: null,
    options: [
      {
        optionId: 41,
        text: "OpenAI",
        yourForecast: 0.6,
        communityAverage: 0.55,
        outcome: null,
      },
      {
        optionId: 42,
        text: "Meta",
        yourForecast: 0.8,
        communityAverage: 0.71,
        outcome: null,
      },
      {
        optionId: 43,
        text: "Apple",
        yourForecast: 0.25,
        communityAverage: 0.4,
        outcome: null,
      },
    ],
    resolved: false,
    closedAt: day(-30),
  },
  {
    propId: 5,
    text: "Bitcoin closes the year above $150,000.",
    category: "Economics",
    kind: "binary",
    yourForecast: null,
    communityAverage: 0.31,
    outcome: null,
    options: [],
    resolved: false,
    closedAt: day(-2),
  },
];

/**
 * Settled. Deliberately mixed: a confident hit, a confident miss (the
 * expensive kind), a near-coin-flip, and both choice kinds.
 */
export const resolvedFixture: PropView[] = [
  {
    propId: 11,
    text: "A US government shutdown before April.",
    category: "US politics",
    kind: "binary",
    yourForecast: 0.3,
    communityAverage: 0.44,
    outcome: false,
    options: [],
    resolved: true,
    closedAt: day(-140),
  },
  {
    propId: 12,
    text: "Cursor raises a round at, or IPOs at, a $30B valuation or above.",
    category: "Technology",
    kind: "binary",
    yourForecast: 0.9,
    communityAverage: 0.62,
    outcome: false,
    options: [],
    resolved: true,
    closedAt: day(-90),
  },
  {
    propId: 13,
    text: "England win the Ashes.",
    category: "Sports",
    kind: "binary",
    yourForecast: 0.65,
    communityAverage: 0.5,
    outcome: false,
    options: [],
    resolved: true,
    closedAt: day(-60),
  },
  {
    propId: 14,
    text: "Anyone in the group changes jobs.",
    category: "Personal",
    kind: "binary",
    yourForecast: 0.8,
    communityAverage: 0.75,
    outcome: true,
    options: [],
    resolved: true,
    closedAt: day(-45),
  },
  {
    propId: 15,
    text: "Which model tops LMArena at the end of the year?",
    category: "Technology",
    kind: "one_of",
    yourForecast: null,
    communityAverage: null,
    outcome: null,
    options: [
      {
        optionId: 151,
        text: "Claude",
        yourForecast: 0.5,
        communityAverage: 0.38,
        outcome: true,
      },
      {
        optionId: 152,
        text: "GPT",
        yourForecast: 0.35,
        communityAverage: 0.42,
        outcome: false,
      },
      {
        optionId: 153,
        text: "Gemini",
        yourForecast: 0.15,
        communityAverage: 0.2,
        outcome: false,
      },
    ],
    resolved: true,
    closedAt: day(-30),
  },
  {
    propId: 16,
    text: "Which of these had a US IPO this year?",
    category: "Economics",
    kind: "any_of",
    yourForecast: null,
    communityAverage: null,
    outcome: null,
    options: [
      {
        optionId: 161,
        text: "Stripe",
        yourForecast: 0.35,
        communityAverage: 0.3,
        outcome: false,
      },
      {
        optionId: 162,
        text: "Databricks",
        yourForecast: 0.7,
        communityAverage: 0.6,
        outcome: true,
      },
      {
        optionId: 163,
        text: "SpaceX",
        yourForecast: 0.1,
        communityAverage: 0.15,
        outcome: false,
      },
    ],
    resolved: true,
    closedAt: day(-20),
  },
  {
    propId: 17,
    text: "The U.S. Men's National Team reaches the World Cup quarterfinals.",
    category: "Sports",
    kind: "binary",
    yourForecast: null,
    communityAverage: 0.28,
    outcome: false,
    options: [],
    resolved: true,
    closedAt: day(-10),
  },
];
