apiVersion: v1
kind: ServiceAccount
metadata:
  name: haruspex-prod-ksa
  namespace: haruspex-prod
  annotations:
    iam.gke.io/gcp-service-account: haruspex-prod-sa@ethans-services.iam.gserviceaccount.com
